spring.application.name=code

management.endpoint.health.show-details=always
management.health.db.enabled=true

spring.datasource.url=jdbc:mysql://172.21.93.218/inventory?usessl=false
spring.datasource.username=root
spring.datasource.password=UnYAMNz2aog27rfLSnrvDoDM
spring.data.mongodb.uri=https://labs-mongo-deep-tight-cpu.mongo.databases.labs.skills.network/library?authSource=admin